spring.application.name : expense-tracking
spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
    open-in-view: false
  web:
    locale: en
  mail:
    host: smtp.gmail.com
    port: 587
    username: expense.tracking.a@gmail.com
    password: esbnfngqzcctzcdd
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            require: true

jwt:
  access-lifetime : PT5M
  refresh-lifetime : PT10H
  secret-key : "14n1ppOOUBo234bONo123o12o13bd13[db1[od1ceb2dgh4gh5trj8rtyYTU1N4I[NBds2df3"

email:
  tokens:
    confirmation-lifetime : P1D
    recover-lifetime : PT30M

logging:
  level:
    root: info
server:
  error:
    include-stacktrace: always
app-url: http://localhost:8080